apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-app
  labels:
    app: kafka-streams-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-streams-app
  template:
    metadata:
      labels:
        app: kafka-streams-app
    spec:
      containers:
      - name: kafka-streams-app
        image: #url for the docker image that is present in the dockerhub
        env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: bootstrapServers
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: apiKey
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: apiSecret
